(()=>{
const ed=document;
const catalog=[
{id:'P001',name:'88元现金券',type:'现金券',amount:88},
{id:'P002',name:'50元存送券',type:'存送券',amount:50},
{id:'P003',name:'30元流水券',type:'流水券',amount:30},
{id:'P004',name:'谢谢参与',type:'谢谢参与',amount:0},
{id:'P005',name:'18元现金券',type:'现金券',amount:18},
{id:'P006',name:'100元存送券',type:'存送券',amount:100},
{id:'P007',name:'10元流水券',type:'流水券',amount:10},
{id:'P008',name:'8元现金券',type:'现金券',amount:8}
];
let sectorCount=8;
let items=[{sector:1,prizeId:'P001',name:'88元现金券',type:'现金券',amount:88,vips:'VIP0-VIP11',stock:100,prob:1,validDays:7,statDays:7,flow:0,maxWin:1,accountLimit:'无限制',accountMode:'',accountValue:'',venue:'',depositType:'',depositReq:0,image:false}];
let editingSector=null,selectedPrize=null,rendering=false;
const q=s=>ed.querySelector(s),qa=s=>[...ed.querySelectorAll(s)];
function onPrizeStep(){const t=q('#tabs .tab.on');return !!(t&&t.textContent.includes('奖品配置'))}
function injectStyle(){if(q('#pcStyle4'))return;const s=ed.createElement('style');s.id='pcStyle4';s.textContent=`
.pc-top{max-width:1380px;margin:0 auto 18px;display:flex;justify-content:space-between;align-items:center;gap:16px}.pc-tools{display:flex;gap:10px;align-items:center}.pc-count{height:38px;border:1px solid #d0d5dd;border-radius:7px;padding:0 10px;background:#fff}.pc-summary{max-width:1380px;margin:0 auto 14px;display:flex;gap:14px;flex-wrap:wrap}.pc-chip{padding:8px 12px;border-radius:7px;background:#f8faff;border:1px solid #dbe7ff;color:#475467}.pc-bad{color:#d92d20;border-color:#fecdca;background:#fff5f5}.pc-good{color:#067647;border-color:#abefc6;background:#ecfdf3}.pc-table{max-width:1380px;margin:0 auto;width:100%;border-collapse:collapse}.pc-table th,.pc-table td{padding:13px 12px;border-bottom:1px solid #eee;text-align:left}.pc-table th{background:#fafafa;color:#667085}.pc-empty{color:#98a2b3}.pc-ops{display:flex;gap:8px}.pc-modal{position:fixed;inset:0;background:rgba(16,24,40,.45);z-index:170;display:none;align-items:center;justify-content:center}.pc-box{width:min(1120px,94vw);max-height:92vh;background:#fff;border-radius:12px;overflow:hidden}.pc-h{padding:20px 24px;border-bottom:1px solid #eaecf0;font-size:20px;font-weight:700;display:flex;justify-content:space-between}.pc-b{padding:24px;max-height:72vh;overflow:auto}.pc-f{padding:16px 24px;border-top:1px solid #eaecf0;display:flex;justify-content:flex-end;gap:10px}.pc-sec{border:1px solid #eaecf0;border-radius:10px;margin-bottom:18px;overflow:hidden}.pc-sec-title{padding:12px 16px;background:#f8fafc;font-weight:700;color:#344054;border-bottom:1px solid #eaecf0}.pc-sec-body{padding:18px;display:grid;grid-template-columns:1fr 1fr;gap:18px 28px}.pc-field.full{grid-column:1/-1}.pc-field label{display:block;font-weight:600;margin-bottom:8px}.pc-input,.pc-select{box-sizing:border-box;width:100%;height:42px;border:1px solid #d0d5dd;border-radius:7px;padding:0 12px;background:#fff}.pc-vips{display:flex;gap:9px;flex-wrap:wrap}.pc-vips label{display:flex;align-items:center;gap:5px;border:1px solid #d0d5dd;padding:7px 9px;border-radius:6px}.pc-upload{height:84px;border:1px dashed #b8c5d6;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#667085;cursor:pointer}.pc-account-options,.pc-account-types{display:flex;gap:24px;flex-wrap:wrap;align-items:center}.pc-limit-box{margin-top:14px;padding:14px;background:#fafbfc;border:1px solid #eaecf0;border-radius:8px}.pc-lib{width:100%;border-collapse:collapse}.pc-lib th,.pc-lib td{padding:12px;border-bottom:1px solid #eee;text-align:left}.pc-lib tr.sel{background:#eff6ff}.pc-warning{margin-top:14px;color:#b54708;background:#fffaeb;border:1px solid #fedf89;padding:10px 12px;border-radius:7px}.pc-muted{color:#98a2b3;font-size:13px;margin-top:6px}@media(max-width:900px){.pc-sec-body{grid-template-columns:1fr}}
`;ed.head.appendChild(s)}
function ensureModals(){
 if(!q('#pcLibraryModal')){const m=ed.createElement('div');m.id='pcLibraryModal';m.className='pc-modal';m.innerHTML=`<div class="pc-box"><div class="pc-h"><span>从奖品库添加</span><span id="pcLibX" style="cursor:pointer">×</span></div><div class="pc-b"><table class="pc-lib"><thead><tr><th></th><th>奖品ID</th><th>奖品名称</th><th>类型</th></tr></thead><tbody id="pcLibBody"></tbody></table></div><div class="pc-f"><button class="btn" id="pcLibCancel">取消</button><button class="btn primary" id="pcLibOk">下一步配置</button></div></div>`;ed.body.appendChild(m);q('#pcLibX').onclick=q('#pcLibCancel').onclick=()=>m.style.display='none';q('#pcLibOk').onclick=()=>{if(!selectedPrize)return alert('请选择奖品');m.style.display='none';openEdit(null,selectedPrize)}}
 if(!q('#pcEditModal')){const m=ed.createElement('div');m.id='pcEditModal';m.className='pc-modal';m.innerHTML=`<div class="pc-box"><div class="pc-h"><span id="pcEditTitle">配置奖品</span><span id="pcEditX" style="cursor:pointer">×</span></div><div class="pc-b">
 <div class="pc-sec"><div class="pc-sec-title">基础配置</div><div class="pc-sec-body">
   <div class="pc-field"><label>扇区</label><select id="pcSector" class="pc-select"></select></div>
   <div class="pc-field"><label>奖品</label><input id="pcPrizeName" class="pc-input" disabled></div>
   <div class="pc-field"><label><span class="req">*</span>金额（元）</label><input id="pcAmount" class="pc-input" type="number" min="0"></div>
   <div class="pc-field" id="pcVenueField"><label><span class="req">*</span>游戏场馆</label><select id="pcVenue" class="pc-select"><option value="">请选择</option><option>体育</option><option>真人</option><option>电子</option><option>电竞</option><option>彩票</option><option>捕鱼</option></select><div class="pc-muted">仅流水券展示</div></div>
   <div class="pc-field" id="pcDepositTypeField"><label><span class="req">*</span>存送类型</label><select id="pcDepositType" class="pc-select"><option value="">请选择</option><option>单笔存款</option><option>累计存款</option><option>单笔存款USDT</option><option>累计存款USDT</option></select><div class="pc-muted">仅存送券展示</div></div>
   <div class="pc-field" id="pcDepositReqField"><label><span class="req">*</span>存款要求（元）</label><input id="pcDepositReq" class="pc-input" type="number" min="0" placeholder="请输入存款要求"></div>
   <div class="pc-field full"><label>奖品展示图（本活动覆盖，可选）</label><div id="pcUpload" class="pc-upload">＋ 上传 / 替换展示图</div></div>
 </div></div>
 <div class="pc-sec"><div class="pc-sec-title">中奖配置</div><div class="pc-sec-body">
   <div class="pc-field"><label><span class="req">*</span>活动库存</label><input id="pcStock" class="pc-input" type="number" min="0"></div>
   <div class="pc-field"><label><span class="req">*</span>中奖概率（%）</label><input id="pcProb" class="pc-input" type="number" min="0" max="100" step="0.01"></div>
   <div class="pc-field"><label><span class="req">*</span>单会员最多中奖数量</label><input id="pcMaxWin" class="pc-input" type="number" min="1"></div>
   <div class="pc-field" id="pcFlowField"><label>流水倍数</label><input id="pcFlow" class="pc-input" type="number" min="0" step="0.1"></div>
 </div></div>
 <div class="pc-sec"><div class="pc-sec-title">统计与有效期</div><div class="pc-sec-body">
   <div class="pc-field"><label><span class="req">*</span>统计日期（天）</label><input id="pcStatDays" class="pc-input" type="number" min="1" placeholder="请输入统计天数"></div>
   <div class="pc-field"><label><span class="req">*</span>有效期（天）</label><input id="pcValid" class="pc-input" type="number" min="1" placeholder="请输入有效天数"></div>
 </div></div>
 <div class="pc-sec"><div class="pc-sec-title">会员范围</div><div class="pc-sec-body">
   <div class="pc-field full"><label><span class="req">*</span>账号限制</label><div class="pc-account-options"><label><input type="radio" name="pcAccountLimit" value="无限制" checked> 无限制</label><label><input type="radio" name="pcAccountLimit" value="限制"> 限制</label></div><div id="pcLimitBox" class="pc-limit-box" style="display:none"><div class="pc-account-types"><label><input type="radio" name="pcAccountMode" value="指定会员" checked> 指定会员</label><label><input type="radio" name="pcAccountMode" value="指定代理"> 指定代理</label><label><input type="radio" name="pcAccountMode" value="排除会员"> 排除会员</label><label><input type="radio" name="pcAccountMode" value="排除代理"> 排除代理</label></div><div style="margin-top:12px"><input id="pcAccountValue" class="pc-input" placeholder="请输入账号，多个账号使用英文逗号分隔"></div></div></div>
   <div class="pc-field full"><label><span class="req">*</span>适用VIP</label><div id="pcVipBox" class="pc-vips"></div></div>
 </div></div>
 <div id="pcThanks" class="pc-warning" style="display:none">“谢谢参与”不发放实际奖励，仅配置扇区和中奖概率；其他发奖字段不生效。</div>
 </div><div class="pc-f"><button class="btn" id="pcEditCancel">取消</button><button class="btn primary" id="pcEditSave">保存</button></div></div>`;ed.body.appendChild(m);q('#pcEditX').onclick=q('#pcEditCancel').onclick=()=>m.style.display='none';q('#pcUpload').onclick=function(){this.textContent='✓ 已上传（点击替换）';this.dataset.done='1'};q('#pcEditSave').onclick=saveEdit;qa('input[name="pcAccountLimit"]').forEach(r=>r.onchange=()=>{q('#pcLimitBox').style.display=q('input[name="pcAccountLimit"]:checked')?.value==='限制'?'block':'none'})}
}
function openLibrary(){ensureModals();selectedPrize=null;const body=q('#pcLibBody');body.innerHTML=catalog.map(x=>`<tr><td><input type="radio" name="pcPrizePick" value="${x.id}"></td><td>${x.id}</td><td>${x.name}</td><td>${x.type}</td></tr>`).join('');body.querySelectorAll('input').forEach(r=>r.onchange=()=>{selectedPrize=catalog.find(x=>x.id===r.value);body.querySelectorAll('tr').forEach(t=>t.classList.remove('sel'));r.closest('tr').classList.add('sel')});q('#pcLibraryModal').style.display='flex'}
function openEdit(sector,prize){ensureModals();editingSector=sector;const existing=sector?items.find(x=>x.sector===sector):null;const p=existing?catalog.find(x=>x.id===existing.prizeId):prize;selectedPrize=p;q('#pcEditTitle').textContent=existing?'编辑奖品配置':'新增奖品配置';q('#pcSector').innerHTML=Array.from({length:sectorCount},(_,i)=>i+1).map(n=>`<option value="${n}" ${(existing?.sector===n)?'selected':''} ${items.some(x=>x.sector===n&&x.sector!==existing?.sector)?'disabled':''}>扇区${n}</option>`).join('');q('#pcPrizeName').value=p.name;q('#pcAmount').value=existing?.amount??p.amount??0;q('#pcStock').value=existing?.stock??(p.type==='谢谢参与'?0:100);q('#pcProb').value=existing?.prob??1;q('#pcMaxWin').value=existing?.maxWin??1;q('#pcStatDays').value=existing?.statDays??7;q('#pcValid').value=existing?.validDays??7;q('#pcFlow').value=existing?.flow??1;q('#pcVenue').value=existing?.venue??'';q('#pcDepositType').value=existing?.depositType??'';q('#pcDepositReq').value=existing?.depositReq??0;qa('input[name="pcAccountLimit"]').forEach(r=>r.checked=r.value===(existing?.accountLimit??'无限制'));qa('input[name="pcAccountMode"]').forEach(r=>r.checked=r.value===(existing?.accountMode||'指定会员'));q('#pcAccountValue').value=existing?.accountValue??'';q('#pcLimitBox').style.display=(existing?.accountLimit==='限制')?'block':'none';q('#pcVipBox').innerHTML=Array.from({length:12},(_,i)=>`<label><input type="checkbox" class="pcVip" value="VIP${i}" checked>VIP${i}</label>`).join('');const isFlow=p.type==='流水券',isDeposit=p.type==='存送券',isThanks=p.type==='谢谢参与';q('#pcVenueField').style.display=isFlow?'block':'none';q('#pcFlowField').style.display=isFlow?'block':'none';q('#pcDepositTypeField').style.display=isDeposit?'block':'none';q('#pcDepositReqField').style.display=isDeposit?'block':'none';q('#pcThanks').style.display=isThanks?'block':'none';['pcAmount','pcStock','pcMaxWin','pcStatDays','pcValid'].forEach(id=>q('#'+id).disabled=isThanks);q('#pcUpload').textContent=existing?.image?'✓ 已上传（点击替换）':'＋ 上传 / 替换展示图';q('#pcUpload').dataset.done=existing?.image?'1':'0';q('#pcEditModal').style.display='flex'}
function saveEdit(){if(!selectedPrize)return;const sector=+q('#pcSector').value,prob=+q('#pcProb').value;if(prob<0||prob>100)return alert('中奖概率请输入0-100');const vs=qa('.pcVip:checked').map(x=>x.value);if(!vs.length)return alert('至少选择一个VIP等级');const isFlow=selectedPrize.type==='流水券',isDeposit=selectedPrize.type==='存送券',isThanks=selectedPrize.type==='谢谢参与';const venue=isFlow?q('#pcVenue').value:'';if(isFlow&&!venue)return alert('请选择游戏场馆');const depositType=isDeposit?q('#pcDepositType').value:'';const depositReq=isDeposit?+q('#pcDepositReq').value:0;if(isDeposit&&!depositType)return alert('请选择存送类型');if(isDeposit&&depositReq<=0)return alert('请输入存款要求');const accountLimit=q('input[name="pcAccountLimit"]:checked')?.value||'无限制';const accountMode=accountLimit==='限制'?(q('input[name="pcAccountMode"]:checked')?.value||'指定会员'):'';const accountValue=accountLimit==='限制'?q('#pcAccountValue').value.trim():'';if(accountLimit==='限制'&&!accountValue)return alert('请输入账号限制内容');const obj={sector,prizeId:selectedPrize.id,name:selectedPrize.name,type:selectedPrize.type,amount:isThanks?0:+q('#pcAmount').value,vips:vs.length===12?'VIP0-VIP11':vs.join('、'),stock:isThanks?0:+q('#pcStock').value,prob,maxWin:isThanks?0:+q('#pcMaxWin').value,statDays:isThanks?0:+q('#pcStatDays').value,validDays:isThanks?0:+q('#pcValid').value,flow:isFlow?+q('#pcFlow').value:0,venue,depositType,depositReq,accountLimit:isThanks?'—':accountLimit,accountMode:isThanks?'':accountMode,accountValue:isThanks?'':accountValue,image:q('#pcUpload').dataset.done==='1'};if(editingSector){const i=items.findIndex(x=>x.sector===editingSector);items[i]=obj}else items.push(obj);items.sort((a,b)=>a.sector-b.sector);q('#pcEditModal').style.display='none';render()}
function remove(sector){if(confirm(`确认移除扇区${sector}的奖品吗？`)){items=items.filter(x=>x.sector!==sector);render()}}
function render(){if(rendering||!onPrizeStep())return;rendering=true;injectStyle();const body=q('#body');if(!body){rendering=false;return}const total=items.reduce((s,x)=>s+Number(x.prob||0),0),used=items.length;body.innerHTML=`<div class="card"><div class="card-h">奖品配置</div><div class="card-b"><div class="notice">从公共奖品库选择奖品，再配置本活动发奖规则。流水券额外配置“游戏场馆、流水倍数”；存送券额外配置“存送类型、存款要求”。</div><div class="pc-top"><div class="pc-tools"><label>转盘扇区数：</label><select id="pcSectorCount" class="pc-count"><option value="8" ${sectorCount===8?'selected':''}>8个扇区</option><option value="10" ${sectorCount===10?'selected':''}>10个扇区</option></select></div><button class="btn primary" id="pcAddPrize">＋ 从奖品库添加</button></div><div class="pc-summary"><div class="pc-chip">已配置：${used}/${sectorCount}</div><div class="pc-chip ${Math.abs(total-100)<0.0001?'pc-good':'pc-bad'}">概率合计：${total.toFixed(2)}%</div><div class="pc-chip">未配置扇区：${sectorCount-used}</div></div><table class="pc-table"><thead><tr><th>扇区</th><th>奖品名称</th><th>类型</th><th>适用VIP</th><th>库存</th><th>概率</th><th>操作</th></tr></thead><tbody>${Array.from({length:sectorCount},(_,i)=>i+1).map(n=>{const x=items.find(v=>v.sector===n);return x?`<tr><td>扇区${n}</td><td>${x.name}</td><td>${x.type}</td><td>${x.vips}</td><td>${x.type==='谢谢参与'?'—':x.stock}</td><td>${x.prob}%</td><td><div class="pc-ops"><button class="btn pc-edit" data-sector="${n}">编辑</button><button class="btn danger pc-del" data-sector="${n}">移除</button></div></td></tr>`:`<tr><td>扇区${n}</td><td colspan="5" class="pc-empty">暂未配置奖品</td><td><button class="btn primary pc-empty-add" data-sector="${n}">选择奖品</button></td></tr>`}).join('')}</tbody></table>${Math.abs(total-100)>0.0001?`<div class="pc-warning">当前所有奖品概率合计为 ${total.toFixed(2)}%，发布前建议校验为100%。“谢谢参与”也计入概率总和。</div>`:''}</div></div>`;q('#pcAddPrize').onclick=openLibrary;q('#pcSectorCount').onchange=e=>{const n=+e.target.value;if(n<sectorCount&&items.some(x=>x.sector>n)){alert('请先移除超出目标扇区数的奖品');e.target.value=sectorCount;return}sectorCount=n;rendering=false;render()};qa('.pc-edit').forEach(b=>b.onclick=()=>openEdit(+b.dataset.sector));qa('.pc-del').forEach(b=>b.onclick=()=>remove(+b.dataset.sector));qa('.pc-empty-add').forEach(b=>b.onclick=()=>{editingSector=null;openLibrary();const target=+b.dataset.sector;const ok=q('#pcLibOk'),old=ok.onclick;ok.onclick=()=>{if(!selectedPrize)return alert('请选择奖品');q('#pcLibraryModal').style.display='none';openEdit(null,selectedPrize);q('#pcSector').value=String(target);ok.onclick=old}});rendering=false}
const tabs=q('#tabs');if(tabs)tabs.addEventListener('click',()=>setTimeout(render,20),true);setTimeout(render,80);
})();