(()=>{
  const ed=document;
  const catalog=[
    {id:'P001',name:'88元现金券',type:'现金券'},
    {id:'P002',name:'50元存送券',type:'存送券'},
    {id:'P003',name:'30元流水券',type:'流水券'},
    {id:'P004',name:'谢谢参与',type:'谢谢参与'},
    {id:'P005',name:'18元现金券',type:'现金券'},
    {id:'P006',name:'100元存送券',type:'存送券'},
    {id:'P007',name:'10元流水券',type:'流水券'},
    {id:'P008',name:'8元现金券',type:'现金券'},
    {id:'P009',name:'58元现金券',type:'现金券'},
    {id:'P010',name:'200元存送券',type:'存送券'}
  ];
  let sectorCount=8;
  let items=[
    {sector:1,prizeId:'P001',name:'88元现金券',type:'现金券',vips:'VIP0-VIP11',stock:100,prob:1,valid:7,flow:1}
  ];
  let editingSector=null, selectedPrize=null, rendering=false;
  function onPrizeStep(){const t=ed.querySelector('#tabs .tab.on');return !!(t&&t.textContent.includes('奖品配置'))}
  function style(){if(ed.getElementById('pcStyle'))return;const s=ed.createElement('style');s.id='pcStyle';s.textContent=`
    .pc-top{max-width:1380px;margin:0 auto 18px;display:flex;justify-content:space-between;align-items:center;gap:16px}.pc-tools{display:flex;gap:10px;align-items:center}.pc-count{height:38px;border:1px solid #d0d5dd;border-radius:7px;padding:0 10px;background:#fff}.pc-summary{max-width:1380px;margin:0 auto 14px;display:flex;gap:14px;flex-wrap:wrap}.pc-chip{padding:8px 12px;border-radius:7px;background:#f8faff;border:1px solid #dbe7ff;color:#475467}.pc-bad{color:#d92d20;border-color:#fecdca;background:#fff5f5}.pc-good{color:#067647;border-color:#abefc6;background:#ecfdf3}.pc-table{max-width:1380px;margin:0 auto;width:100%;border-collapse:collapse}.pc-table th,.pc-table td{padding:13px 12px;border-bottom:1px solid #eee;text-align:left}.pc-table th{background:#fafafa;color:#667085}.pc-empty{color:#98a2b3}.pc-ops{display:flex;gap:8px}.pc-modal{position:fixed;inset:0;background:rgba(16,24,40,.45);z-index:170;display:none;align-items:center;justify-content:center}.pc-box{width:min(980px,92vw);max-height:88vh;background:#fff;border-radius:12px;overflow:hidden}.pc-h{padding:20px 24px;border-bottom:1px solid #eaecf0;font-size:20px;font-weight:700;display:flex;justify-content:space-between}.pc-b{padding:22px 24px;max-height:66vh;overflow:auto}.pc-f{padding:16px 24px;border-top:1px solid #eaecf0;display:flex;justify-content:flex-end;gap:10px}.pc-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px 24px}.pc-field label{display:block;font-weight:600;margin-bottom:8px}.pc-input,.pc-select{width:100%;height:42px;border:1px solid #d0d5dd;border-radius:7px;padding:0 12px;background:#fff}.pc-vips{display:flex;gap:9px;flex-wrap:wrap}.pc-vips label{display:flex;align-items:center;gap:5px;border:1px solid #d0d5dd;padding:7px 9px;border-radius:6px}.pc-lib{width:100%;border-collapse:collapse}.pc-lib th,.pc-lib td{padding:12px;border-bottom:1px solid #eee;text-align:left}.pc-lib tr.sel{background:#eff6ff}.pc-warning{margin-top:14px;color:#b54708;background:#fffaeb;border:1px solid #fedf89;padding:10px 12px;border-radius:7px}.pc-upload{height:84px;border:1px dashed #b8c5d6;border-radius:8px;display:flex;align-items:center;justify-content:center;color:#667085;cursor:pointer}@media(max-width:900px){.pc-grid{grid-template-columns:1fr}}
  `;ed.head.appendChild(s)}
  function ensureModals(){if(!ed.getElementById('pcLibraryModal')){const m=ed.createElement('div');m.id='pcLibraryModal';m.className='pc-modal';m.innerHTML=`<div class="pc-box"><div class="pc-h"><span>从奖品库添加</span><span id="pcLibX" style="cursor:pointer">×</span></div><div class="pc-b"><table class="pc-lib"><thead><tr><th></th><th>奖品ID</th><th>奖品名称</th><th>类型</th></tr></thead><tbody id="pcLibBody"></tbody></table></div><div class="pc-f"><button class="btn" id="pcLibCancel">取消</button><button class="btn primary" id="pcLibOk">下一步配置</button></div></div>`;ed.body.appendChild(m);m.querySelector('#pcLibX').onclick=m.querySelector('#pcLibCancel').onclick=()=>m.style.display='none';m.querySelector('#pcLibOk').onclick=()=>{if(!selectedPrize)return alert('请选择奖品');m.style.display='none';openEdit(null,selectedPrize)}}
    if(!ed.getElementById('pcEditModal')){const m=ed.createElement('div');m.id='pcEditModal';m.className='pc-modal';m.innerHTML=`<div class="pc-box"><div class="pc-h"><span id="pcEditTitle">配置奖品</span><span id="pcEditX" style="cursor:pointer">×</span></div><div class="pc-b"><div class="pc-grid"><div class="pc-field"><label>扇区</label><select id="pcSector" class="pc-select"></select></div><div class="pc-field"><label>奖品</label><input id="pcPrizeName" class="pc-input" disabled></div><div class="pc-field"><label><span class="req">*</span>活动库存</label><input id="pcStock" class="pc-input" type="number" min="0"></div><div class="pc-field"><label><span class="req">*</span>中奖概率（%）</label><input id="pcProb" class="pc-input" type="number" min="0" max="100" step="0.01"></div><div class="pc-field"><label>有效期（天）</label><input id="pcValid" class="pc-input" type="number" min="0"></div><div class="pc-field"><label>流水倍数</label><input id="pcFlow" class="pc-input" type="number" min="0" step="0.1"></div><div class="pc-field" style="grid-column:1/-1"><label><span class="req">*</span>适用VIP</label><div id="pcVipBox" class="pc-vips"></div></div><div class="pc-field" style="grid-column:1/-1"><label>奖品展示图（本活动覆盖，可选）</label><div id="pcUpload" class="pc-upload">＋ 上传 / 替换展示图</div></div></div><div id="pcThanks" class="pc-warning" style="display:none">“谢谢参与”不发放实际奖励：库存、有效期、流水倍数不参与发奖，仅按配置概率占用扇区。</div></div><div class="pc-f"><button class="btn" id="pcEditCancel">取消</button><button class="btn primary" id="pcEditSave">保存</button></div></div>`;ed.body.appendChild(m);m.querySelector('#pcEditX').onclick=m.querySelector('#pcEditCancel').onclick=()=>m.style.display='none';m.querySelector('#pcUpload').onclick=function(){this.textContent='✓ 已上传（点击替换）';this.dataset.done='1'};m.querySelector('#pcEditSave').onclick=saveEdit}
  }
  function openLibrary(){ensureModals();selectedPrize=null;const used=new Set(items.map(x=>x.prizeId));const body=ed.getElementById('pcLibBody');body.innerHTML=catalog.map(x=>`<tr data-id="${x.id}" class="${used.has(x.id)?'used':''}"><td><input type="radio" name="pcPrizePick" value="${x.id}" ${used.has(x.id)?'disabled':''}></td><td>${x.id}</td><td>${x.name}${used.has(x.id)?'（已添加）':''}</td><td>${x.type}</td></tr>`).join('');body.querySelectorAll('input:not(:disabled)').forEach(r=>r.onchange=()=>{selectedPrize=catalog.find(x=>x.id===r.value);body.querySelectorAll('tr').forEach(t=>t.classList.remove('sel'));r.closest('tr').classList.add('sel')});ed.getElementById('pcLibraryModal').style.display='flex'}
  function openEdit(sector,prize){ensureModals();editingSector=sector;const existing=sector?items.find(x=>x.sector===sector):null;const p=existing?catalog.find(x=>x.id===existing.prizeId):prize;selectedPrize=p;const m=ed.getElementById('pcEditModal');ed.getElementById('pcEditTitle').textContent=existing?'编辑奖品配置':'新增奖品配置';ed.getElementById('pcSector').innerHTML=Array.from({length:sectorCount},(_,i)=>i+1).map(n=>`<option value="${n}" ${(existing?.sector===n)?'selected':''} ${items.some(x=>x.sector===n&&x.sector!==existing?.sector)?'disabled':''}>扇区${n}</option>`).join('');ed.getElementById('pcPrizeName').value=p.name;ed.getElementById('pcStock').value=existing?.stock??(p.type==='谢谢参与'?0:100);ed.getElementById('pcProb').value=existing?.prob??1;ed.getElementById('pcValid').value=existing?.valid??7;ed.getElementById('pcFlow').value=existing?.flow??1;ed.getElementById('pcVipBox').innerHTML=Array.from({length:12},(_,i)=>`<label><input type="checkbox" class="pcVip" value="VIP${i}" checked>VIP${i}</label>`).join('');ed.getElementById('pcThanks').style.display=p.type==='谢谢参与'?'block':'none';m.style.display='flex'}
  function saveEdit(){const sector=+ed.getElementById('pcSector').value,stock=+ed.getElementById('pcStock').value,prob=+ed.getElementById('pcProb').value,valid=+ed.getElementById('pcValid').value,flow=+ed.getElementById('pcFlow').value;if(!selectedPrize)return;if(prob<0||prob>100)return alert('中奖概率请输入0-100');const vs=[...ed.querySelectorAll('.pcVip:checked')].map(x=>x.value);if(!vs.length)return alert('至少选择一个VIP等级');const obj={sector,prizeId:selectedPrize.id,name:selectedPrize.name,type:selectedPrize.type,vips:vs.length===12?'VIP0-VIP11':vs.join('、'),stock:selectedPrize.type==='谢谢参与'?0:stock,prob,valid:selectedPrize.type==='谢谢参与'?0:valid,flow:selectedPrize.type==='谢谢参与'?0:flow};if(editingSector){const i=items.findIndex(x=>x.sector===editingSector);items[i]=obj}else items.push(obj);items.sort((a,b)=>a.sector-b.sector);ed.getElementById('pcEditModal').style.display='none';render()}
  function remove(sector){if(confirm(`确认移除扇区${sector}的奖品吗？`)){items=items.filter(x=>x.sector!==sector);render()}}
  function render(){if(rendering||!onPrizeStep())return;rendering=true;style();const body=ed.getElementById('body');if(!body){rendering=false;return}const total=items.reduce((s,x)=>s+Number(x.prob||0),0),used=items.length;body.innerHTML=`<div class="card"><div class="card-h">奖品配置</div><div class="card-b"><div class="notice">从公共奖品库选择奖品，再配置本活动库存、概率、VIP范围、有效期及流水规则。建议转盘使用8或10个扇区。</div><div class="pc-top"><div class="pc-tools"><label>转盘扇区数：</label><select id="pcSectorCount" class="pc-count"><option value="8" ${sectorCount===8?'selected':''}>8个扇区</option><option value="10" ${sectorCount===10?'selected':''}>10个扇区</option></select></div><button class="btn primary" id="pcAddPrize">＋ 从奖品库添加</button></div><div class="pc-summary"><div class="pc-chip">已配置：${used}/${sectorCount}</div><div class="pc-chip ${Math.abs(total-100)<0.0001?'pc-good':'pc-bad'}">概率合计：${total.toFixed(2)}%</div><div class="pc-chip">未配置扇区：${sectorCount-used}</div></div><table class="pc-table"><thead><tr><th>扇区</th><th>奖品名称</th><th>类型</th><th>适用VIP</th><th>库存</th><th>概率</th><th>有效期/流水</th><th>操作</th></tr></thead><tbody>${Array.from({length:sectorCount},(_,i)=>i+1).map(n=>{const x=items.find(v=>v.sector===n);return x?`<tr><td>扇区${n}</td><td>${x.name}</td><td>${x.type}</td><td>${x.vips}</td><td>${x.type==='谢谢参与'?'—':x.stock}</td><td>${x.prob}%</td><td>${x.type==='谢谢参与'?'—':`${x.valid}天 / ${x.flow}倍流水`}</td><td><div class="pc-ops"><button class="btn link pc-edit" data-sector="${n}">编辑</button><button class="btn danger pc-del" data-sector="${n}">移除</button></div></td></tr>`:`<tr><td>扇区${n}</td><td colspan="6" class="pc-empty">暂未配置奖品</td><td><button class="btn primary pc-empty-add" data-sector="${n}">选择奖品</button></td></tr>`}).join('')}</tbody></table>${Math.abs(total-100)>0.0001?`<div class="pc-warning">当前所有奖品概率合计为 ${total.toFixed(2)}%，发布活动前建议校验为100%。“谢谢参与”也计入概率总和。</div>`:''}</div></div>`;body.querySelector('#pcAddPrize').onclick=openLibrary;body.querySelector('#pcSectorCount').onchange=e=>{const n=+e.target.value;if(n<sectorCount&&items.some(x=>x.sector>n)){alert('请先移除超出目标扇区数的奖品');e.target.value=sectorCount;return}sectorCount=n;rendering=false;render();return};body.querySelectorAll('.pc-edit').forEach(b=>b.onclick=()=>openEdit(+b.dataset.sector));body.querySelectorAll('.pc-del').forEach(b=>b.onclick=()=>remove(+b.dataset.sector));body.querySelectorAll('.pc-empty-add').forEach(b=>b.onclick=()=>{editingSector=null;openLibrary();const target=+b.dataset.sector;const ok=ed.getElementById('pcLibOk');const old=ok.onclick;ok.onclick=()=>{if(!selectedPrize)return alert('请选择奖品');ed.getElementById('pcLibraryModal').style.display='none';openEdit(null,selectedPrize);ed.getElementById('pcSector').value=String(target);ok.onclick=old}});rendering=false}
  const tabs=ed.getElementById('tabs');if(tabs)tabs.addEventListener('click',()=>setTimeout(render,20),true);setTimeout(render,80);
})();